# -- Theme Options --

# Site description.
description = "Freelance System Administrator - Linux, Network & Server Administration"

# Copyright owner name.
copyright = "Michal Jirka"

# Whether to optimize images per view port.
optimizeImg = true

# Whether to enable copy button in code blocks.
enableCodeCopy = true

# Show the icon that switches between dark and light themes when clicked.
showThemeSwitcher = true

# Default theme to start from. Dark theme by default.
defaultTheme = "dark"  # Valid Options: light, dark, auto

# When enabled, highlight the current menu item in the menu bar.
highlightCurrentMenu = true

# The sections to display in the recent articles list.
mainSections = ["posts"]

# Whether to remove Hugo and theme attribution in the footer.
removeAttribution = false

# Add the last build date to the footer.
lastUpdate = true

# Whether to show anchor links in headings.
showHeadingAnchors = true

# Whether to enable search.
enableSearch = true

# Homepage settings
[homepage]
# Whether to show recent items on the homepage.
showRecent = false
# Heading label for recent items.
showRecentLabel = "Featured"
# Number of recent items to show.
showRecentItems = 4
# Whether to display a "Show more" link.
showMore = false
showMoreDest = "/posts"

[homepage.profile]
# Displayed at the top of your homepage.
headline = "ðŸ‘‹ Freelance System Administrator"

# Image position.
where = "right"  # Options: right, left, top

# Article settings
[article]
# Whether to display article dates.
showDate = true
# Whether to display modified dates of articles.
showModDate = true
# Whether to display reading time of articles.
showReadingTime = true
# Whether to display tags mentioned in the front matter.
showTags = true
# Whether to display next/previous article links in the article footer.
showPagination = true
# Whether to reverse the direction of next/previous article links.
invertPagination = true
# Whether to display the table of contents on articles.
showToC = true
# Whether to open the Table of Contents when the page is loaded.
openToC = false
showComments = false
# Whether to display breadcrumbs
showBreadcrumbs = true

# List template settings
[list]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = true
# Whether to display pages as a card
cardView = true
# Whether to display thumbnail in list card view.
showThumbnail = false
# Whether to display RSS link
showRSS = true

# Taxonomy settings
[taxonomy]
# Whether to show counts of each taxonomy term.
showCount = true
# Whether to display taxonomies as a grid of cards.
cardView = true

# Term settings
[term]
# Whether to group articles by year.
groupByYear = false
# Whether to display breadcrumbs
showBreadcrumbs = true
# Whether to display pages as a card
cardView = true
# Whether to display RSS link
showRSS = true

# Social links
[[social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/jirkami/"

[[social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jirkami/"

[[social]]
name = "Email"
icon = "email"
url = "mailto:george@infracore.cz"

[[social]]
name = "Phone"
icon = "phone"
url = "tel:+420608556186"

[[social]]
name = "Telegram"
icon = "telegram"
url = "https://t.me/jirkami"

[[social]]
name = "WhatsApp"
icon = "whatsapp"
url = "https://wa.me/420608556186"
