#################### default parameters ############################
favicon = "images/favicon.png"
logo = "images/infracore_logo_light.svg"
logo_darkmode = "images/infracore_logo_light.svg"
logo_width = "300px"
logo_height = "75px"
logo_webp = false
logo_text = "Michal Jirka"
navbar_fixed = true
theme_switcher = false
theme_default = "dark"
mainSections = ["blog"]
contact_form_action = "#"
google_tag_manager = ""
google_adsense = ""
custom_script = ""
copyright = "© 2024 Michal Jirka - Infracore. Všechna práva vyhrazena."

# Preloader
[preloader]
enable = false
preloader = ""

# Navigation button (disabled to avoid duplicate Kontakt in menu)
[navigation_button]
enable = false
label = "Kontakt"
link = "contact"

# search
[search]
enable = false
primary_color = "#0066CC"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# announcement
[announcement]
enable = false
expire_days = 7
content = ""

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["System Administrator", "DevOps", "Linux", "Cloud", "AWS", "Azure", "Infracore", "Brno"]
description = "Michal Jirka - Specialista na systémovou správu a automatizaci IT infrastruktury. 20+ let zkušeností s Linux, cloud technologiemi a síťovou infrastrukturou."
author = "Michal Jirka"
twitter = ""
image = "images/og-image.png"

# site verifications
[site_verification]
google = ""
bing = ""
baidu = ""
facebook = ""
mastodon = ""

# cookies
[cookies]
enable = false
expire_days = 60
content = "Tyto stránky používají cookies. Pokračováním v prohlížení souhlasíte s jejich použitím."
button = "Souhlasím"

# diagrams
[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]

# google map
[google_map]
enable = false
map_api_key = ""
map_latitude = "49.1951"
map_longitude = "16.6068"
map_marker = "images/marker.png"

# Subscription
[subscription]
enable = false
mailchimp_form_action = ""
mailchimp_form_name = ""
